version: '3'
services:
  web:

    image: flask_app:3.0


    
    ports:
      - "4000:5000"
  
    volumes:
      - "/Users/mohanadgad/Desktop/learn-docker/flask_app/:/code"


    networks:
      - app
    deploy:
      replicas: 3
    
  database:

  
    image: mysql/mysql-server:5.7
 
    env_file:
      - ./.env
    

    volumes:
      - "/Users/mohanadgad/Desktop/learn-docker/flask_app/db/init.sql:/docker-entrypoint-initdb.d/init.sql"

    deploy:
      replicas: 2

    networks:
      - app
  viz:

    # Visualizer image for swarm cluster.

    image: dockersamples/visualizer

    # Mapping container ports to host port

    ports: 

      - "8080:8080"

    # Mounting docker socket to container.
    
    volumes:

      - "/var/run/docker.sock:/var/run/docker.sock"
    
    networks:
      - app

networks:
  app: